spring:
    profiles:
        active: dev        
camel.springboot.shutdownTimeout: 2      
---

spring:
    profiles: mock
    
startRoute: direct:input
#fromRoute : file:data/input/dev?delete=true&readLock=none
toRoute1: mock:output
    
message: DEV Environment
    
---

spring:
    profiles: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/my_db
        username: root
        password: 11111111
    
startRoute: timer:hello?period=10s
fromRoute : file:data/input/dev?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=Success.tx
    
message: DEV Environment
    
---    
spring:
    profiles: stage

startRoute: timer:hello?period=10s
fromRoute : file:data/input/stage?delete=true&readLock=none
toRoute1: file:data/output    

message: STAGE Environment

---    
spring:
    profiles: prod
    
startRoute: timer:hello?period=10s
fromRoute : file:data/input/prod?delete=true&readLock=none
toRoute1: file:data/output    

message: PROD Environment

---    